apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-gateway-api-micro-function
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: api-micro-function
          servicePort: 8080