apiVersion: networking.k8s.io/v2
kind: Ingress
metadata:
  name: api-gateway-api-micro-function
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service: api-micro-function
          servicePort: 8080