apiVersion: v1
kind: Service
metadata:
  name: api-micro-function-service
spec:
  selector:
    app: api-micro-function
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: LoadBalancer
